services:
    postgres:
        image: postgres:17
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
        ports:
            - ${POSTGRES_PORT}:5432
    graphql-engine:
        image: hasura/graphql-engine:latest
        container_name: hasura
        restart: always
        ports:
            - 8081:8080
        depends_on:
            - postgres
        environment:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
          HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
          HASURA_GRAPHQL_DEV_MODE: "true"
          HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - "${REDIS_PORT}:6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: redis-server --requirepass $REDIS_PASSWORD
    subconnect-node:
        container_name: subconnect
        image: sweatpotato/subconnect:dev
        restart: always
        ports:
            - "30333:30333"
            - "9933:9933"
            - "9944:9944"
        command: |
            --unsafe-rpc-external
            --rpc-cors all
            --dev
    # nest:
    #     container_name: nest
    #     restart: always
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./
    #     env_file: 
    #         - .env
    #     ports:
    #         - ${PORT}:8000
